<?xml version="1.0"?>
<package format="2">
  <name>my_robot</name>
  <version>0.0.0</version>
  <description>The my_robot package</description>

  <!-- One maintainer tag required, multiple allowed, one person per tag -->
  <maintainer email="mohamed@todo.todo">Mohamed Raessa</maintainer>
  
  <!-- At least one license tag is needed-->
  <license>opensource</license>

  <!-- ament_cmake instead of catkin-->
  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>ros_gz</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>
